
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\tModLoader.targets" />
  <PropertyGroup>
    <AssemblyName>Ascent</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Assets\Textures\Projectiles\Hostile\BossAttacks\Aster\MadStar.png" />
  </ItemGroup>
  <ItemGroup>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Assets\Effects\" />
    <Folder Include="Assets\Textures\Items\Weapons\Ranged\Guns\" />
    <Folder Include="Assets\Textures\Particles\" />
    <Folder Include="Content\Items\Weapons\Magic\" />
    <Folder Include="Content\Items\Weapons\Summon\" />
    <Folder Include="Content\NPCs\Bosses\TheImpaled\" />
    <Folder Include="Content\NPCs\Events\Starfall\Minibosses\" />
  </ItemGroup>
</Project>